import { useState, useRef } from "react"
import InputForm from "./components/InputForm"
import LoadingState from "./components/LoadingState"
import ReportCard from "./components/ReportCard"
import EmailCard from "./components/EmailCard"
import { Download } from "lucide-react"
import jsPDF from "jspdf"
import html2canvas from "html2canvas"

export default function App() {

  const [isLoading, setIsLoading] = useState(false)
  const [currentStep, setCurrentStep] = useState(0)
  const [result, setResult] = useState(null)
  const [error, setError] = useState(null)
  const resultsRef = useRef(null)

  const startFakeProgress = () => {
    setCurrentStep(1)
    let step = 1
    const interval = setInterval(() => {
      step += 1
      setCurrentStep(step)
      if (step >= 6) clearInterval(interval)
    }, 2500)
    return interval
  }

  const handleSubmit = async ({ company_name, product }) => {
    setIsLoading(true)
    setResult(null)
    setError(null)

    const interval = startFakeProgress()

    try {
      const response = await fetch(
        `${import.meta.env.VITE_API_URL}/analyze`,
        {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ company_name, product }), // ✅ fixed — was 'data'
        }
      )

      let data
      try {
        data = await response.json()
      } catch {
        throw new Error("Server returned an invalid response")
      }

      if (!response.ok) {
        throw new Error(data?.detail || "Something went wrong")
      }

      clearInterval(interval)
      setCurrentStep(6)

      setTimeout(() => {
        setResult(data)
        setIsLoading(false)
        setCurrentStep(0)
      }, 800)

    } catch (err) {
      clearInterval(interval)
      setError(err.message)
      setIsLoading(false)
      setCurrentStep(0)
    }
  }
  
  return (
    <div className="min-h-screen bg-gray-900 text-white">
      <div className="fixed inset-0 bg-gradient-to-br from-blue-950/20 via-gray-900 to-purple-950/20 pointer-events-none" />

      <div className="relative z-10 container mx-auto px-4 py-12">
        {!isLoading && !result && (
          <InputForm onSubmit={handleSubmit} isLoading={isLoading} />
        )}

        {isLoading && <LoadingState currentStep={currentStep} />}

        {error && (
          <div className="max-w-2xl mx-auto mt-8 bg-red-500/10 border border-red-500/30 rounded-2xl p-6 text-center">
            <p className="text-red-400 font-medium">{error}</p>
            <button
              onClick={() => setError(null)}
              className="mt-4 text-gray-400 hover:text-white text-sm underline"
            >
              Try again
            </button>
          </div>
        )}

        {result && (
          <div>
            <div className="flex items-center justify-between mb-8">
              <div>
                <h2 className="text-2xl font-bold text-white">
                  Intelligence Report —{" "}
                  <span className="text-blue-400">{result.company_name}</span>
                </h2>
                <p className="text-gray-500 text-sm mt-1">
                  Generated by AI Sales Intelligence Agent
                </p>
              </div>

              <div className="flex gap-3">
                <button
                  onClick={() => setResult(null)}
                  className="bg-gray-700/50 hover:bg-gray-600/50 border border-gray-600/50 text-gray-300 font-medium px-4 py-2 rounded-xl transition-all duration-200 text-sm"
                >
                  New Search
                </button>

              </div>
            </div>

            <div ref={resultsRef} className="grid grid-cols-2 gap-6">
              <ReportCard
                report={result.report}
                companyName={result.company_name}
              />
              <EmailCard
                email={result.email}
                companyName={result.company_name}
              />
            </div>
          </div>
        )}
      </div>
    </div>
  )
}